[package]
name = "tree"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
description = "A simple CLI tool to print directory trees with configurable ignore patterns"
license = "MIT"
repository = "https://github.com/githubrobbi/tree"
keywords = ["cli", "tree", "directory", "filesystem", "tool"]
categories = ["command-line-utilities", "filesystem"]

[[bin]]
name = "tree"
path = "src/bin/tree.rs"

[dependencies]
anyhow = "1.0.98"
ignore = "0.4.23"
clap = { version = "4.5.41", features = ["derive"] }
walkdir = "2.0"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.0"
assert_cmd = "2.0"
predicates = "3.0"
proptest = "1.0"
