coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "benches/"
  - "examples/"

github_checks:
  annotations: true
